### ISSUE TITLE
enhancement - encrypt entire contents of json file

### ISSUE THREAD

**Issue by hdNguyenPTR** [tsmx/secure-config-tool#1]
we would like to take a json file
.json 
and encrypt entire contents
.json.enc
then decrypt it at run time with key - no need for regex patterns. 

https://github.com/nareshv/secure-conf/blob/master/examples/test.js#L26

we want to use your key from environment variables to dynamically decrypt file contents

eg. 
include 
```javascript
import encSettings "config.json.enc"
var settings = encSettings.decrypt();
```

**Comment by tsmx** [comment]
Hi!

Encrypting the entire file (meaning ALL of its contents, keys & values) is not the original intention of my package @tsmx/secure-config and this supporting tool as it has some major drawbacks:
- the result would not be a valid JSON anymore
- the result would be completely unreadable for humans, which makes the handling extremely difficult

Since the additional gain of security is very small I defintively do _not recommend_ to encrypt the entire file.

But: Nevertheless you can achieve your goal very easy with the provided library [@tsmx/string-crypto](https://www.npmjs.com/package/@tsmx/string-crypto) which I also use in this project.

**Encrypt an entire JSON file**

```js
const sc = require('@tsmx/string-crypto');
const fs = require('fs');
const jsonFile = require('test.json');
let encryptedJson = sc.encrypt(JSON.stringify(jsonFile));
fs.writeFileSync('test.json.enc', encryptedJson);
```

**Decrypt the JSON back**

```js
const sc = require('@tsmx/string-crypto');
const fs = require('fs');
let decryptedJsonFile = JSON.parse(sc.decrypt(fs.readFileSync('test.json.enc').toString()));
```

Note: @tsmx/string-crypto by default uses the environment variable `ENCRYPTION_KEY`. If you need to use an environment variable with another name, simply pass the key directly...

```js
sc.encrypt(text, { key: process.env['YOUR_VAR_NAME'] });
sc.decrypt(text, { key: process.env['YOUR_VAR_NAME'] });
```

Hope that helps!

Kind regards

P.S.: closing the issue as it's not relevant for this project
