### ISSUE TITLE
json parsing with arrays of objects

### ISSUE THREAD

**Issue by mdaouas** [tsmx/secure-config-tool#5]
Hi,
Why is the traverse json call parameter flattenArray forced to false on first call when creating the encrypted file this is preventing encryption on object elements contained in an array. Is it done on any purpose?
It would be nice to make it optional so encryption would work on those arrays of objects
Thanks

**Comment by tsmx** [comment]
Hi @mdaouas, sorry for the late reply. Obviously I missed the notification on your issue. 

At first look, the arrays are flattened because the secure-config library also uses flattenArray=true on decryption (see line 47 in the secure-config library: https://github.com/tsmx/secure-config/blob/master/secure-config.js#L47). I'll investigate further why this was implemented that way and get back to you.

Kind Regards

**Comment by tsmx** [comment]
Should be possible to add support for encrypted properties of objects in arrays. Impacts at least on the following points:

- secure-config: decryption
-  secure-config-tool: creation of encrypted config file
- secure-config-tool: update of hmac values
- doumentation and tests

Feature idea [support for encrypted properties of objects in arrays](https://github.com/tsmx/secure-config/projects/1#card-91301205) was added to the [secure-config project](https://github.com/tsmx/secure-config/projects/1).

**Comment by tsmx** [comment]
[secure-config 2.1.0](https://github.com/tsmx/secure-config/releases/tag/v2.1.0) with support for encrypted props of objects in arrays released. Prerequisites to adapt secure-config-tool are set.

**Comment by tsmx** [comment]
Feature branch [array-object-encryption](https://github.com/tsmx/secure-config-tool/tree/array-object-encryption) created.

**Comment by tsmx** [comment]
Version 2.2.0 with enhancement released.
